# Generated by Django 3.2.10 on 2022-04-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IAWE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('active', models.FloatField()),
                ('reactive', models.FloatField()),
                ('apparent', models.FloatField()),
                ('f', models.FloatField()),
                ('vo', models.FloatField()),
                ('pf', models.FloatField()),
                ('cu', models.FloatField()),
                ('device', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'iawe',
                'managed': False,
            },
        ),
    ]
